## 모듈과 패키지

In [1]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 묶은 것 (폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [2]:
import math # math라는 모듈이 있어요
print(math.pi)
print(math.sqrt(4)) # sqrt는 제곱근 구해줌

3.141592653589793
2.0


In [3]:
import math as m # math를 가져오는 데 m 이라는 이름으로 가져온다
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [4]:
from math import pi, sqrt
print(pi) # math.pi 는 오히려 안됨
print(sqrt(4))

3.141592653589793
2.0


In [5]:
from math import * # * 이 all 이란 뜻
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [6]:
from math import sqrt as s
print(s(4))

2.0


In [7]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [8]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [9]:
import numpy as np # numpy는 라이브러리(패키지와 모듈들을 모아놓음)다 (numerical python)
a=np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
import numpy.random
numpy.random.randn(3,3) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

array([[ 1.54670563, -0.78546115,  0.44382322],
       [-1.52843523,  1.34631412,  0.89858698],
       [ 0.7112449 , -0.56263417,  0.66669444]])

In [11]:
import numpy.random as nr
nr.randn(3,3)

array([[-0.59978917,  0.62212908, -0.11162812],
       [ 0.92389257, -1.96450031, -0.32415027],
       [-0.09073041,  2.45079377,  0.81519871]])

In [12]:
from numpy.random import randn
randn(3,3)

array([[ 1.36987211, -0.88350884, -0.27859945],
       [ 0.03637495, -1.80972497,  0.89449214],
       [ 1.23724728, -1.89107672, -0.74985394]])

In [13]:
from numpy.random import *
rand(3,3) # uniform distribution

array([[0.16951138, 0.7494053 , 0.7389184 ],
       [0.09874731, 0.67186281, 0.37424579],
       [0.56138253, 0.46322174, 0.87326656]])

In [14]:
from numpy.random import randn as rn
rn(3,3)

array([[-1.19434301,  0.020035  , -0.15346814],
       [-0.37704511,  1.46739614, -0.84513401],
       [-0.24807783, -0.76393708, -1.00683588]])

In [15]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[ 0.90722669 -0.1000073  -0.27967764]
 [ 1.03583905 -2.14534256 -0.58927311]
 [ 1.639611    0.34902795 -1.56262002]]
[[0.31259499 0.96860313 0.1371499 ]
 [0.24326492 0.87805513 0.49891763]
 [0.91344385 0.71024568 0.01318246]]


## numpy 본격적으로

In [16]:
import numpy as np
a=np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=np.array([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
[1.  2.  3.1 4. ]


In [17]:
A=np.array([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as np 는 실행 했다 치고 작성
# A=np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수

[[1 2 3]
 [3 4 5]]
(2, 3)
2
6


In [18]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0 에서부터 1 포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

[5 7 9]


In [20]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [21]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy 의 인덱싱과 슬라이싱

In [22]:
a=np.array([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [23]:
# 행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[4 5 6]
[4 6]
[3 6 9]


In [24]:
# 3차원 행렬 인덱싱
A=np.array([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

a=np.array([[[1,2,3,4]]]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6
(1, 1, 4)


In [25]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰 애들을 100으로 바꿔줘)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=np.array([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2   3 100]
 [100   3 100   3]]
[[1 2]
 [7 8]]
[1 2]


In [26]:
# array로 인덱싱
a=np.array([1,2,3,4,5])
A=a[2]
print(A)
A=a[ np.array(2) ] # np.array를 안에다가?
print(A)
A=a[ np.array([2,3,4]) ]
print(A)
A=a[ np.array([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=np.array([[1,2,3],[4,5,6]])
print(a[0])
A=a[ np.array([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

3
3
[3 4 5]
[[3 3 3]
 [4 4 4]]
[1 2 3]
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]


In [27]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ array(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ np.array([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ array ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ np.array([1,1,2,2,2]) ])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
[2]
[2]
[2]
[[3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


## numpy의 여러 함수들

In [28]:
A=np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)

[[ 0.48596228  0.77166156  1.15319848]
 [ 0.67833382 -0.12547177 -0.5202217 ]
 [ 0.66653606 -0.9092626  -1.07230676]]
[[0.44991194 0.559257   0.55748641]
 [0.26583609 0.99746098 0.26050966]
 [0.05708738 0.45088271 0.37756914]]


In [29]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[ 1.81979844  0.2022171   1.75173588]
 [ 0.34768237 -1.05600973  0.26702557]
 [-1.11517621 -1.21038847 -0.15498778]]
[[1.81979844 0.2022171  1.75173588]
 [0.34768237 1.05600973 0.26702557]
 [1.11517621 1.21038847 0.15498778]]
[[1.34899905 0.44968556 1.32353159]
 [0.58964597 1.02762334 0.51674517]
 [1.05601904 1.10017656 0.39368487]]
[[6.17061459 1.22411373 5.76460065]
 [1.41578248 0.34784102 1.30607384]
 [0.3278575  0.29808146 0.85642565]]
[[ 0.59872575 -1.59841341  0.56060723]
 [-1.05646596  0.0544974  -1.32041087]
 [ 0.10901243  0.19094136 -1.86440903]]
1.0
1.0
1.0
[[ 2.  0.  2.]
 [ 0. -1.  0.]
 [-1. -1. -0.]]
[[ 1.82  0.2   1.75]
 [ 0.35 -1.06  0.27]
 [-1.12 -1.21 -0.15]]
[[ 1.  0.  1.]
 [ 0. -2.  0.]
 [-2. -2. -1.]]
[[ 2.  1.  2.]
 [ 1. -1.  1.]
 [-1. -1. -0.]]


In [30]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [31]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [32]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1)) # 1D array로 바꿔버림
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(np.min(A))
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A))
print(np.argmax(A,axis=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

[[-0.60523058  0.45763557 -0.39361458  0.05707284]
 [ 1.5225225   0.97640359  0.99878339 -0.2613232 ]
 [-1.22315858 -0.02896569 -0.88962234 -0.41247383]]
1.5225224996426958
[1.5225225  0.97640359 0.99878339 0.05707284]
[ 0.45763557  1.5225225  -0.02896569]
[[1.5225225  0.97640359 0.99878339 0.05707284]]
[[ 0.45763557]
 [ 1.5225225 ]
 [-0.02896569]]
-1.223158583158644
[-1.22315858 -0.02896569 -0.88962234 -0.41247383]
[-0.60523058 -0.2613232  -1.22315858]
4
[1 1 1 0]
[1 0 1]


In [33]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

a=np.random.randn(6,1)
print(a)
print(a.sort(axis=0))

print(np.max(a))
print(a.max())

[[ 1.53815451]
 [ 0.68955321]
 [ 1.22541549]
 [-1.36321306]
 [ 0.73269423]
 [-0.84855078]]
[[-1.36321306]
 [-0.84855078]
 [ 0.68955321]
 [ 0.73269423]
 [ 1.22541549]
 [ 1.53815451]]
[[ 1.53815451]
 [ 1.22541549]
 [ 0.73269423]
 [ 0.68955321]
 [-0.84855078]
 [-1.36321306]]
[[-0.97579127]
 [ 2.77511343]
 [ 2.58136628]
 [-0.14012528]
 [-0.30585142]
 [-2.04380357]]
None
2.775113425700631
2.775113425700631


In [34]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) # standard deviation 표준 편차

print(A.sum(axis=1, keepdims=True))
print(A.mean(axis=1, keepdims=True))
print(A.std())

[[-0.1785558   1.26731628  1.43468432  2.02559875]
 [ 0.84966687  0.40778372  0.83537864  0.5789691 ]
 [-2.02653973  0.17447931 -1.43854222  1.58518823]]
5.515427457498677
[ 4.54904354  2.67179833 -1.70541441]
[[ 4.54904354]
 [ 2.67179833]
 [-1.70541441]]
0.4596189547915564
[ 1.13726089  0.66794958 -0.4263536 ]
[[ 1.13726089]
 [ 0.66794958]
 [-0.4263536 ]]
1.1512733132693038
[[ 4.54904354]
 [ 2.67179833]
 [-1.70541441]]
[[ 1.13726089]
 [ 0.66794958]
 [-0.4263536 ]]
1.1512733132693038


In [35]:
A=np.random.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

[4 1 2 4 2 4 4 3 1 4 4 4]
(12,)
[[[4 1 2]
  [4 2 4]]

 [[4 3 1]
  [4 4 4]]]
3


In [36]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A=np.random.randn(4,3,6)
print(A.transpose(0,2,1).shape)

9
[[9]]
[[9]]
(4, 6, 3)


In [37]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [38]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [39]:
A=np.ones((3,4))
B=np.zeros((3,4))
C=np.vstack([A,B])
D=np.hstack([A,B])
E=np.block([[A],[B]])
F=np.block([A,B])
G=np.block([ [[A]], [[B]] ])

print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [40]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [41]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
